@tool
class_name PickySprite2D
extends Sprite2D

const LIGHT_ENCODER = preload("res://addons/picky-pixels/nodes/picky_sprite_2d/light_encoder.material")
const UNLIT = preload("res://addons/picky-pixels/nodes/picky_sprite_2d/unlit.material")

var _data: PickySprite2DData
## Data used for rendering a PickySprite2D.
## This Resource includes the encoded texture,
## decoding shader, and other data used for compatility.
## This Resource is generated by the PickyPixels editor.
@export var data: PickySprite2DData:
	get: return _data
	set(d):
		if not is_inside_tree():
			await ready
		_data = d
		
		if _data == null or _data.texture == null:
			texture = null
			return
		
		# TODO also check if there is not the correct shader on the viewport
		if Engine.is_editor_hint():
			texture = _data.base_textures.back()
			material = UNLIT
		else:
			texture = _data.texture
			material = LIGHT_ENCODER


func _ready():
	if Engine.is_editor_hint():
		material = UNLIT
	else:
		material = LIGHT_ENCODER
