@tool
class_name PickySprite2D
extends Sprite2D

const LIGHT_ENCODE = preload("res://addons/picky-pixels/nodes/picky_sprite_2d/light_encode.res")

var _data: PickySprite2DData
## Data used for rendering a PickySprite2D.
## This Resource includes the encoded texture,
## decoding shader, and other data used for compatility.
## This Resource is generated by the PickyPixels editor.
@export var data: PickySprite2DData:
	get: return _data
	set(d):
		if not is_inside_tree():
			await ready
		_data = d
		
		_update_texture()


func _update_texture():
	if _data == null or _data.texture == null:
		texture = null
		return
	
	# TODO also check if there is not the correct shader on the viewport
	if Engine.is_editor_hint() and OS.has_feature("editor"):
		texture = _data.base_textures.back()
	else:
		texture = _data.texture


func _ready():
	material = LIGHT_ENCODE
	_update_texture()
