@tool
class_name PickySprite2D
extends CanvasGroup

@onready var _sprite_2d: Sprite2D = $Sprite2D

var _data: PickySprite2DData
## Data used for rendering a PickySprite2D.
## This Resource includes the encoded texture,
## decoding shader, and other data used for compatility.
## This Resource is generated by the PickyPixels editor.
@export var data: PickySprite2DData:
	get: return _data
	set(d):
		if not is_inside_tree():
			await ready
		_data = d
		
		if _data == null:
			_sprite_2d.texture = null
			material = null
		else:
			_sprite_2d.texture = ImageTexture.create_from_image(_data.image)
			material = _data.shader_material
